/**
 * Email Service for Scheduled Reports
 * Provides email delivery functionality for automated report distribution
 */

import nodemailer from 'nodemailer';
import path from 'path';

/**
 * Create email transporter based on environment configuration
 */
function createTransporter() {
  // Production: Use SMTP configuration from environment
  if (process.env.NODE_ENV === 'production' || process.env.SMTP_HOST) {
    return nodemailer.createTransporter({
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: process.env.SMTP_SECURE === 'true', // true for 465, false for other ports
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASSWORD
      },
      from: process.env.SMTP_FROM || 'noreply@shotspot.app'
    });
  }
  
  // Development/Test: Use ethereal.email test account
  // Note: In production, you should configure real SMTP settings
  if (process.env.NODE_ENV === 'development') {
    console.log('⚠️  Using test email account. Configure SMTP_* environment variables for production.');
  }
  
  // Return null transporter for test environment to prevent actual emails
  return null;
}

/**
 * Generate HTML email template for report delivery
 */
function generateReportEmailHTML(options) {
  const {
    reportName,
    reportType,
    teamName,
    generatedBy,
    downloadUrl,
    expiresAt
  } = options;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      border-radius: 8px 8px 0 0;
      text-align: center;
    }
    .header h1 {
      margin: 0;
      font-size: 24px;
    }
    .content {
      background: #f8f9fa;
      padding: 30px;
      border: 1px solid #dee2e6;
      border-top: none;
    }
    .report-info {
      background: white;
      padding: 20px;
      border-radius: 8px;
      margin: 20px 0;
      border-left: 4px solid #667eea;
    }
    .report-info p {
      margin: 8px 0;
    }
    .report-info strong {
      color: #667eea;
      font-weight: 600;
    }
    .download-button {
      display: inline-block;
      background: #667eea;
      color: white;
      padding: 12px 30px;
      text-decoration: none;
      border-radius: 6px;
      font-weight: 600;
      margin: 20px 0;
      transition: background 0.3s;
    }
    .download-button:hover {
      background: #764ba2;
    }
    .footer {
      text-align: center;
      color: #6c757d;
      font-size: 12px;
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #dee2e6;
    }
    .warning {
      background: #fff3cd;
      border: 1px solid #ffc107;
      padding: 15px;
      border-radius: 6px;
      margin: 15px 0;
      color: #856404;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🏐 ShotSpot Report Ready</h1>
  </div>
  
  <div class="content">
    <p>Your scheduled report has been generated and is ready for download.</p>
    
    <div class="report-info">
      <p><strong>Report Name:</strong> ${reportName}</p>
      <p><strong>Report Type:</strong> ${reportType}</p>
      ${teamName ? `<p><strong>Team:</strong> ${teamName}</p>` : ''}
      <p><strong>Generated By:</strong> ${generatedBy}</p>
      <p><strong>Generated At:</strong> ${new Date().toLocaleString()}</p>
    </div>
    
    ${downloadUrl ? `
    <div style="text-align: center;">
      <a href="${downloadUrl}" class="download-button">Download Report</a>
    </div>
    ` : ''}
    
    ${expiresAt ? `
    <div class="warning">
      ⚠️ <strong>Note:</strong> This report will be automatically deleted on ${new Date(expiresAt).toLocaleDateString()}.
      Please download it before then if you need to keep a copy.
    </div>
    ` : ''}
  </div>
  
  <div class="footer">
    <p>This is an automated message from ShotSpot - Korfball Statistics Platform</p>
    <p>If you have any questions, please contact your team administrator.</p>
  </div>
</body>
</html>
  `;
}

/**
 * Generate plain text version of report email
 */
function generateReportEmailText(options) {
  const {
    reportName,
    reportType,
    teamName,
    generatedBy,
    downloadUrl,
    expiresAt
  } = options;

  let text = 'ShotSpot Report Ready\n\n';
  text += 'Your scheduled report has been generated and is ready for download.\n\n';
  text += 'Report Details:\n';
  text += `- Report Name: ${reportName}\n`;
  text += `- Report Type: ${reportType}\n`;
  if (teamName) text += `- Team: ${teamName}\n`;
  text += `- Generated By: ${generatedBy}\n`;
  text += `- Generated At: ${new Date().toLocaleString()}\n\n`;
  
  if (downloadUrl) {
    text += `Download Link: ${downloadUrl}\n\n`;
  }
  
  if (expiresAt) {
    text += `⚠️ Note: This report will be automatically deleted on ${new Date(expiresAt).toLocaleDateString()}.\n`;
    text += 'Please download it before then if you need to keep a copy.\n\n';
  }
  
  text += '---\n';
  text += 'This is an automated message from ShotSpot - Korfball Statistics Platform\n';
  
  return text;
}

/**
 * Send report email to recipients
 * 
 * @param {Object} options - Email options
 * @param {string[]} options.recipients - Array of email addresses
 * @param {string} options.subject - Email subject
 * @param {string} options.reportName - Name of the report
 * @param {string} options.reportType - Type of report (game, team, season, etc.)
 * @param {string} [options.teamName] - Team name if applicable
 * @param {string} options.generatedBy - Username of person who created the schedule
 * @param {string} [options.downloadUrl] - Full URL to download the report
 * @param {string} [options.filePath] - Path to attachment file
 * @param {Date} [options.expiresAt] - When the report expires
 * @returns {Promise<Object>} - Result of email sending
 */
export async function sendReportEmail(options) {
  const {
    recipients,
    subject,
    reportName,
    reportType,
    teamName,
    generatedBy,
    downloadUrl,
    filePath,
    expiresAt
  } = options;

  // Validate recipients
  if (!recipients || !Array.isArray(recipients) || recipients.length === 0) {
    throw new Error('At least one recipient email address is required');
  }

  // Don't actually send emails in test environment
  if (process.env.NODE_ENV === 'test') {
    if (process.env.NODE_ENV !== 'test') {
      console.log('📧 [TEST MODE] Would send email:', {
        to: recipients,
        subject,
        reportName
      });
    }
    return {
      success: true,
      messageId: 'test-message-id',
      recipients,
      testMode: true
    };
  }

  const transporter = createTransporter();
  
  if (!transporter) {
    if (process.env.NODE_ENV !== 'test') {
      console.warn('⚠️  Email transporter not configured. Skipping email send.');
    }
    return {
      success: false,
      error: 'Email service not configured',
      recipients
    };
  }

  // Generate email content
  const html = generateReportEmailHTML({
    reportName,
    reportType,
    teamName,
    generatedBy,
    downloadUrl,
    expiresAt
  });

  const text = generateReportEmailText({
    reportName,
    reportType,
    teamName,
    generatedBy,
    downloadUrl,
    expiresAt
  });

  // Prepare email options
  const mailOptions = {
    from: process.env.SMTP_FROM || 'noreply@shotspot.app',
    to: recipients.join(', '),
    subject: subject || `ShotSpot Report: ${reportName}`,
    text,
    html
  };

  // Attach file if provided
  if (filePath) {
    mailOptions.attachments = [
      {
        filename: path.basename(filePath),
        path: filePath
      }
    ];
  }

  try {
    const info = await transporter.sendMail(mailOptions);
    
    if (process.env.NODE_ENV !== 'test') {
      console.log('✅ Email sent successfully:', info.messageId);
      if (process.env.NODE_ENV === 'development' && info.preview) {
        console.log('📧 Preview URL:', nodemailer.getTestMessageUrl(info));
      }
    }

    return {
      success: true,
      messageId: info.messageId,
      recipients,
      previewUrl: process.env.NODE_ENV === 'development' ? nodemailer.getTestMessageUrl(info) : null
    };
  } catch (error) {
    console.error('❌ Failed to send email:', error);
    return {
      success: false,
      error: error.message,
      recipients
    };
  }
}

/**
 * Verify email configuration
 * Useful for checking SMTP settings on startup
 */
export async function verifyEmailConfig() {
  if (process.env.NODE_ENV === 'test') {
    return { verified: true, message: 'Test environment - email verification skipped' };
  }

  const transporter = createTransporter();
  
  if (!transporter) {
    return {
      verified: false,
      message: 'Email service not configured. Set SMTP_* environment variables.'
    };
  }

  try {
    await transporter.verify();
    return {
      verified: true,
      message: 'Email configuration verified successfully'
    };
  } catch (error) {
    return {
      verified: false,
      message: `Email configuration error: ${error.message}`
    };
  }
}

export default {
  sendReportEmail,
  verifyEmailConfig
};
